name: pugs_detection
channels:
  - conda-forge
dependencies:
  - python=3.12.8
  - osmnx=2.0.1
  - geopandas=1.0.1
  - torchgeo=0.6.2
  - pytorch=2.6.0
  - openeo=0.37.0
  - rioxarray=0.18.2
  - rasterio=1.4.3
  - numpy=1.26.4
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - pip # TBD
  - pip: # TBD
    - python-dotenv
    - mkdocs